name: Enforce Different Team Approvals

on:
  pull_request:
    branches:
      - develop  # Trigger on PRs targeting the 'develop' branch
    types: 
      - opened
      - review_requested
      - synchronize
      - edited

jobs:
  check-team-approvals:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Approvals
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            
            const reviews = pr.data.reviews;
            const team1Approvers = reviews.filter(r => r.user.login.includes('team-1') && r.state === 'APPROVED');
            const team2Approvers = reviews.filter(r => r.user.login.includes('team-2') && r.state === 'APPROVED');

            if (team1Approvers.length > 0 && team2Approvers.length > 0) {
              console.log("Both teams have approved the PR.");
            } else {
              core.setFailed('Both Team 1 and Team 2 must approve the PR.');
            }
